import type { Food } from "@/lib/types";

const ts = {
  createdAt: "2026-02-20T00:00:00Z",
  updatedAt: "2026-02-20T00:00:00Z",
};

export const BRANDED_FOODS: Food[] = [
  {
    id: "brand_quick_oats",
    name: "VitalFit Protein Porridge Vanille",
    categoryId: "cat_fruehstueck",
    source: "Herstellerangabe",
    sourceId: "hersteller",
    sourceVersion: "2026-03",
    isBranded: true,
    manufacturer: "VitalFit GmbH",
    allergens: ["Gluten", "Milch"],
    additives: ["E322", "E471"],
    co2PerPortion: 0.85,
    tags: ["High Protein", "Diabetes"],
    baseAmount: 100,
    portionSizes: [
      { label: "Portion (55 g)", amount: 55 },
      { label: "Shaker (70 g)", amount: 70 },
    ],
    nutrients: [
      { nutrientId: "energie", amount: 360 },
      { nutrientId: "eiweiss", amount: 34 },
      { nutrientId: "fett", amount: 8 },
      { nutrientId: "kohlenhydrate", amount: 35 },
      { nutrientId: "zucker", amount: 4 },
      { nutrientId: "ballaststoffe", amount: 7 },
      { nutrientId: "natrium", amount: 120 },
      { nutrientId: "calcium", amount: 210 },
    ],
    ...ts,
  },
  {
    id: "brand_ready_meal",
    name: "ClinicCare Renal Menü Bolognese",
    categoryId: "cat_fertiggerichte",
    source: "Herstellerangabe",
    sourceId: "hersteller",
    isBranded: true,
    manufacturer: "ClinicCare Nutrition",
    allergens: ["Sellerie", "Milch"],
    additives: ["E250", "E412"],
    co2PerPortion: 2.1,
    baseAmount: 100,
    portionSizes: [
      { label: "Beutel (320 g)", amount: 320 },
    ],
    nutrients: [
      { nutrientId: "energie", amount: 120 },
      { nutrientId: "eiweiss", amount: 10 },
      { nutrientId: "fett", amount: 4 },
      { nutrientId: "kohlenhydrate", amount: 12 },
      { nutrientId: "natrium", amount: 420 },
      { nutrientId: "kalium", amount: 140 },
      { nutrientId: "phosphor", amount: 95 },
    ],
    ...ts,
  },
  {
    id: "brand_beverage",
    name: "NutriPlus Trinknahrung Kaffee",
    categoryId: "cat_getraenke",
    source: "Herstellerangabe",
    sourceId: "hersteller",
    isBranded: true,
    manufacturer: "NutriPlus Medical",
    allergens: ["Milch"],
    additives: ["E415"],
    co2PerPortion: 0.5,
    baseAmount: 100,
    portionSizes: [
      { label: "Flasche (200 ml)", amount: 200 },
    ],
    nutrients: [
      { nutrientId: "energie", amount: 150 },
      { nutrientId: "eiweiss", amount: 6 },
      { nutrientId: "fett", amount: 6 },
      { nutrientId: "kohlenhydrate", amount: 18 },
      { nutrientId: "zucker", amount: 12 },
      { nutrientId: "natrium", amount: 75 },
      { nutrientId: "calcium", amount: 120 },
    ],
    ...ts,
  },
  {
    id: "brand_snack",
    name: "GreenBite Low-Carb Riegel Erdbeer",
    categoryId: "cat_snacks",
    source: "Herstellerangabe",
    sourceId: "hersteller",
    isBranded: true,
    manufacturer: "GreenBite AG",
    allergens: ["Schalenfrüchte", "Soja"],
    additives: ["E330"],
    co2PerPortion: 0.22,
    baseAmount: 100,
    portionSizes: [
      { label: "Riegel (40 g)", amount: 40 },
    ],
    nutrients: [
      { nutrientId: "energie", amount: 280 },
      { nutrientId: "eiweiss", amount: 22 },
      { nutrientId: "fett", amount: 12 },
      { nutrientId: "kohlenhydrate", amount: 8 },
      { nutrientId: "zucker", amount: 3 },
      { nutrientId: "ballaststoffe", amount: 18 },
    ],
    ...ts,
  },
];
