import type { Patient } from "@/lib/types";

const ts = { createdAt: "2026-01-15T00:00:00Z", updatedAt: "2026-01-15T00:00:00Z" };

export const PATIENTS: Patient[] = [
  {
    id: "patient_1",
    firstName: "Maria",
    lastName: "Schneider",
    dateOfBirth: "1978-03-14",
    gender: "w",
    email: "maria.schneider@example.de",
    phone: "0171-1234567",
    street: "Hauptstr. 12",
    zip: "80331",
    city: "München",
    insuranceProvider: "AOK Bayern",
    insuranceNumber: "A123456789",
    indications: ["Adipositas"],
    notes: "Motivation zur Gewichtsreduktion sehr hoch. Familienanamnese: Diabetes Typ 2.",
    ...ts,
  },
  {
    id: "patient_2",
    firstName: "Thomas",
    lastName: "Weber",
    dateOfBirth: "1965-11-22",
    gender: "m",
    email: "t.weber@example.de",
    phone: "0160-9876543",
    street: "Lindenweg 5",
    zip: "50667",
    city: "Köln",
    insuranceProvider: "Techniker Krankenkasse",
    insuranceNumber: "T987654321",
    indications: ["Diabetes mellitus Typ 2"],
    notes: "Seit 2023 diagnostiziert. Medikation: Metformin 1000mg. Regelmäßige HbA1c-Kontrolle.",
    ...ts,
    updatedAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "patient_3",
    firstName: "Lisa",
    lastName: "Hoffmann",
    dateOfBirth: "1992-07-08",
    gender: "w",
    email: "lisa.hoffmann@example.de",
    phone: "0152-3456789",
    street: "Mozartstr. 23",
    zip: "70173",
    city: "Stuttgart",
    insuranceProvider: "Barmer",
    insuranceNumber: "B456789012",
    indications: ["Zöliakie"],
    notes: "Diagnose seit 2020. Strikte glutenfreie Ernährung notwendig.",
    ...ts,
  },
  {
    id: "patient_4",
    firstName: "Jürgen",
    lastName: "Fischer",
    dateOfBirth: "1955-01-30",
    gender: "m",
    email: "j.fischer@example.de",
    phone: "0173-5678901",
    street: "Gartenstr. 7",
    zip: "20095",
    city: "Hamburg",
    insuranceProvider: "DAK-Gesundheit",
    insuranceNumber: "D567890123",
    indications: ["Adipositas"],
    notes: "BMI > 35. Komorbiditäten: Hypertonie, Schlafapnoe. Ziel: 15 kg Gewichtsreduktion.",
    amputations: ["unterschenkel"],
    ...ts,
  },
  {
    id: "patient_5",
    firstName: "Anna",
    lastName: "Müller",
    dateOfBirth: "1988-05-19",
    gender: "w",
    email: "anna.mueller@example.de",
    phone: "0176-2345678",
    street: "Schillerplatz 3",
    zip: "10115",
    city: "Berlin",
    insuranceProvider: "AOK Nordost",
    insuranceNumber: "A234567890",
    indications: ["Nahrungsmittelallergie"],
    notes: "Multiple Allergien: Nüsse, Soja, Sellerie. Anaphylaxie-Risiko bei Nüssen.",
    ...ts,
  },
  {
    id: "patient_6",
    firstName: "Klaus",
    lastName: "Becker",
    dateOfBirth: "1970-09-03",
    gender: "m",
    email: "k.becker@example.de",
    phone: "0151-6789012",
    street: "Am Markt 15",
    zip: "60311",
    city: "Frankfurt am Main",
    insuranceProvider: "IKK classic",
    insuranceNumber: "I678901234",
    indications: ["Diabetes mellitus Typ 2"],
    notes: "Neu diagnostiziert. Motivation für Lebensstiländerung vorhanden. Sportlich aktiv.",
    amputations: ["hand"],
    ...ts,
  },
  {
    id: "patient_7",
    firstName: "Sophie",
    lastName: "Klein",
    dateOfBirth: "1995-12-11",
    gender: "w",
    email: "sophie.klein@example.de",
    phone: "0157-8901234",
    street: "Bergstr. 42",
    zip: "90402",
    city: "Nürnberg",
    insuranceProvider: "Techniker Krankenkasse",
    insuranceNumber: "T345678901",
    indications: ["Adipositas"],
    notes: "BMI 32. Beruflich viel unterwegs, unregelmäßige Mahlzeiten.",
    ...ts,
  },
];
