import type { PerformanceMetric, LoadTestResult, DatabaseQueryStat, SystemResource } from "@/lib/types";

export const PERFORMANCE_KPIS: PerformanceMetric[] = [
  {
    id: "perf_response",
    label: "Antwortzeit",
    value: 45,
    unit: "ms",
    target: 100,
    status: "gut",
    trend: "down",
  },
  {
    id: "perf_throughput",
    label: "Durchsatz",
    value: 1240,
    unit: "req/s",
    target: 1000,
    status: "gut",
    trend: "up",
  },
  {
    id: "perf_cache",
    label: "Cache-Trefferrate",
    value: 94.2,
    unit: "%",
    target: 90,
    status: "gut",
    trend: "up",
  },
  {
    id: "perf_db",
    label: "DB-Abfragezeit",
    value: 12,
    unit: "ms",
    target: 50,
    status: "gut",
    trend: "flat",
  },
  {
    id: "perf_error",
    label: "Fehlerrate",
    value: 0.03,
    unit: "%",
    target: 0.5,
    status: "gut",
    trend: "down",
  },
  {
    id: "perf_uptime",
    label: "Verfügbarkeit",
    value: 99.97,
    unit: "%",
    target: 99.9,
    status: "gut",
    trend: "flat",
  },
];

export const LOAD_TEST_RESULTS: LoadTestResult[] = [
  {
    id: "lt_1",
    testName: "Basis-Last",
    concurrentUsers: 10,
    avgResponseMs: 32,
    p95ResponseMs: 58,
    p99ResponseMs: 85,
    errorRate: 0,
    throughputRps: 420,
    timestamp: "2026-04-10T06:00:00Z",
  },
  {
    id: "lt_2",
    testName: "Normal-Betrieb",
    concurrentUsers: 50,
    avgResponseMs: 45,
    p95ResponseMs: 92,
    p99ResponseMs: 145,
    errorRate: 0,
    throughputRps: 980,
    timestamp: "2026-04-10T06:15:00Z",
  },
  {
    id: "lt_3",
    testName: "Hohe Last",
    concurrentUsers: 100,
    avgResponseMs: 78,
    p95ResponseMs: 180,
    p99ResponseMs: 320,
    errorRate: 0.01,
    throughputRps: 1240,
    timestamp: "2026-04-10T06:30:00Z",
  },
  {
    id: "lt_4",
    testName: "Spitzenlast",
    concurrentUsers: 500,
    avgResponseMs: 195,
    p95ResponseMs: 520,
    p99ResponseMs: 890,
    errorRate: 0.12,
    throughputRps: 1680,
    timestamp: "2026-04-10T06:45:00Z",
  },
  {
    id: "lt_5",
    testName: "Stresstest",
    concurrentUsers: 1000,
    avgResponseMs: 480,
    p95ResponseMs: 1200,
    p99ResponseMs: 2400,
    errorRate: 1.8,
    throughputRps: 1520,
    timestamp: "2026-04-10T07:00:00Z",
  },
];

export const DATABASE_QUERY_STATS: DatabaseQueryStat[] = [
  {
    id: "dbq_food_search",
    queryName: "Lebensmittel-Suche",
    tableName: "foods",
    avgDurationMs: 8,
    callsPerMinute: 340,
    cacheHitRate: 96.5,
    lastExecuted: "2026-04-10T09:58:00Z",
  },
  {
    id: "dbq_patient_lookup",
    queryName: "Patienten-Abfrage",
    tableName: "patients",
    avgDurationMs: 4,
    callsPerMinute: 120,
    cacheHitRate: 91.2,
    lastExecuted: "2026-04-10T09:57:00Z",
  },
  {
    id: "dbq_nutrient_agg",
    queryName: "Nährstoff-Aggregation",
    tableName: "nutrients",
    avgDurationMs: 22,
    callsPerMinute: 85,
    cacheHitRate: 78.4,
    lastExecuted: "2026-04-10T09:55:00Z",
  },
  {
    id: "dbq_recipe_join",
    queryName: "Rezept-Zusammenführung",
    tableName: "recipes × foods",
    avgDurationMs: 35,
    callsPerMinute: 60,
    cacheHitRate: 82.1,
    lastExecuted: "2026-04-10T09:56:00Z",
  },
  {
    id: "dbq_meal_plan",
    queryName: "Ernährungsplan-Laden",
    tableName: "meal_plans",
    avgDurationMs: 15,
    callsPerMinute: 45,
    cacheHitRate: 88.7,
    lastExecuted: "2026-04-10T09:54:00Z",
  },
  {
    id: "dbq_protocol_insert",
    queryName: "Protokoll-Speicherung",
    tableName: "protocols",
    avgDurationMs: 18,
    callsPerMinute: 25,
    cacheHitRate: 0,
    lastExecuted: "2026-04-10T09:50:00Z",
  },
  {
    id: "dbq_lab_values",
    queryName: "Laborwerte-Trend",
    tableName: "lab_values",
    avgDurationMs: 28,
    callsPerMinute: 30,
    cacheHitRate: 74.3,
    lastExecuted: "2026-04-10T09:52:00Z",
  },
];

export const SYSTEM_RESOURCES: SystemResource[] = [
  { id: "res_cpu", label: "CPU", currentValue: 34, maxValue: 100, unit: "%" },
  { id: "res_ram", label: "RAM", currentValue: 6.2, maxValue: 16, unit: "GB" },
  { id: "res_disk", label: "Speicher", currentValue: 120, maxValue: 500, unit: "GB" },
  { id: "res_network", label: "Netzwerk", currentValue: 45, maxValue: 1000, unit: "Mbit/s" },
];

export const RESPONSE_TIME_HISTORY: Array<{ timestamp: string; value: number }> = [
  { timestamp: "00:00", value: 38 },
  { timestamp: "02:00", value: 32 },
  { timestamp: "04:00", value: 28 },
  { timestamp: "06:00", value: 35 },
  { timestamp: "08:00", value: 52 },
  { timestamp: "09:00", value: 68 },
  { timestamp: "10:00", value: 75 },
  { timestamp: "11:00", value: 62 },
  { timestamp: "12:00", value: 48 },
  { timestamp: "13:00", value: 55 },
  { timestamp: "14:00", value: 71 },
  { timestamp: "15:00", value: 65 },
  { timestamp: "16:00", value: 58 },
  { timestamp: "17:00", value: 45 },
  { timestamp: "18:00", value: 42 },
  { timestamp: "19:00", value: 38 },
  { timestamp: "20:00", value: 35 },
  { timestamp: "21:00", value: 30 },
  { timestamp: "22:00", value: 28 },
  { timestamp: "23:00", value: 25 },
];
