import type { NutritionProtocol } from "@/lib/types";

const ts = (date: string) => ({ createdAt: `${date}T00:00:00Z`, updatedAt: `${date}T00:00:00Z` });

export const PROTOCOLS: NutritionProtocol[] = [
  {
    id: "protocol_1",
    patientId: "patient_1",
    title: "3-Tage-Ernährungsprotokoll März",
    type: "ernaehrungsprotokoll",
    startDate: "2026-03-10",
    endDate: "2026-03-12",
    notes: "Patientin hat Protokoll gewissenhaft geführt. Wochenende nicht erfasst.",
    days: [
      {
        date: "2026-03-10",
        entries: [
          { id: "pe_1_1", foodId: "food_vollkornbrot", amount: 80, mealSlot: "fruehstueck", time: "07:30" },
          { id: "pe_1_2", foodId: "food_butter", amount: 10, mealSlot: "fruehstueck", time: "07:30" },
          { id: "pe_1_3", foodId: "food_gouda", amount: 30, mealSlot: "fruehstueck", time: "07:30" },
          { id: "pe_1_4", foodId: "food_apfel", amount: 150, mealSlot: "snack_vormittag", time: "10:00" },
          { id: "pe_1_5", foodId: "food_reis", amount: 200, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_1_6", foodId: "food_haehnchenbrust", amount: 150, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_1_7", foodId: "food_brokkoli", amount: 150, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_1_8", foodId: "food_olivenoel", amount: 10, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_1_9", foodId: "food_joghurt", amount: 150, mealSlot: "snack_nachmittag", time: "15:30" },
          { id: "pe_1_10", foodId: "food_heidelbeere", amount: 100, mealSlot: "snack_nachmittag", time: "15:30" },
          { id: "pe_1_11", foodId: "food_nudeln", amount: 200, mealSlot: "abendessen", time: "19:00" },
          { id: "pe_1_12", foodId: "food_tomate", amount: 100, mealSlot: "abendessen", time: "19:00" },
          { id: "pe_1_13", foodId: "food_olivenoel", amount: 15, mealSlot: "abendessen", time: "19:00" },
        ],
      },
      {
        date: "2026-03-11",
        entries: [
          { id: "pe_2_1", foodId: "food_haferflocken", amount: 60, mealSlot: "fruehstueck", time: "07:00" },
          { id: "pe_2_2", foodId: "food_vollmilch", amount: 200, mealSlot: "fruehstueck", time: "07:00" },
          { id: "pe_2_3", foodId: "food_banane", amount: 120, mealSlot: "fruehstueck", time: "07:00" },
          { id: "pe_2_4", foodId: "food_mandeln", amount: 25, mealSlot: "snack_vormittag", time: "10:30" },
          { id: "pe_2_5", foodId: "food_kartoffel", amount: 250, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_2_6", foodId: "food_lachs", amount: 150, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_2_7", foodId: "food_spinat", amount: 150, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_2_8", foodId: "food_rapsoel", amount: 10, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_2_9", foodId: "food_apfel", amount: 130, mealSlot: "snack_nachmittag", time: "16:00" },
          { id: "pe_2_10", foodId: "food_vollkornbrot", amount: 100, mealSlot: "abendessen", time: "19:30" },
          { id: "pe_2_11", foodId: "food_ei", amount: 120, mealSlot: "abendessen", time: "19:30" },
          { id: "pe_2_12", foodId: "food_tomate", amount: 80, mealSlot: "abendessen", time: "19:30" },
          { id: "pe_2_13", foodId: "food_gurke", amount: 100, mealSlot: "abendessen", time: "19:30" },
        ],
      },
      {
        date: "2026-03-12",
        entries: [
          { id: "pe_3_1", foodId: "food_vollkornbrot", amount: 60, mealSlot: "fruehstueck", time: "08:00" },
          { id: "pe_3_2", foodId: "food_magerquark", amount: 150, mealSlot: "fruehstueck", time: "08:00" },
          { id: "pe_3_3", foodId: "food_honig", amount: 15, mealSlot: "fruehstueck", time: "08:00" },
          { id: "pe_3_4", foodId: "food_erdbeere", amount: 100, mealSlot: "snack_vormittag", time: "10:00" },
          { id: "pe_3_5", foodId: "food_rote_linsen", amount: 200, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_3_6", foodId: "food_karotte", amount: 100, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_3_7", foodId: "food_zwiebel", amount: 50, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_3_8", foodId: "food_olivenoel", amount: 10, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_3_9", foodId: "food_walnuesse", amount: 20, mealSlot: "snack_nachmittag", time: "15:00" },
          { id: "pe_3_10", foodId: "food_putenbrust", amount: 150, mealSlot: "abendessen", time: "18:30" },
          { id: "pe_3_11", foodId: "food_paprika", amount: 100, mealSlot: "abendessen", time: "18:30" },
          { id: "pe_3_12", foodId: "food_zucchini", amount: 120, mealSlot: "abendessen", time: "18:30" },
          { id: "pe_3_13", foodId: "food_rapsoel", amount: 10, mealSlot: "abendessen", time: "18:30" },
        ],
      },
    ],
    ...ts("2026-03-12"),
  },
  {
    id: "protocol_2",
    patientId: "patient_2",
    title: "24h-Recall Februar",
    type: "24h_recall",
    startDate: "2026-02-20",
    endDate: "2026-02-20",
    notes: "Telefonisches 24h-Recall. Patient konnte sich gut erinnern.",
    days: [
      {
        date: "2026-02-20",
        entries: [
          { id: "pe_4_1", foodId: "food_vollkornbrot", amount: 100, mealSlot: "fruehstueck", time: "06:30" },
          { id: "pe_4_2", foodId: "food_butter", amount: 15, mealSlot: "fruehstueck", time: "06:30" },
          { id: "pe_4_3", foodId: "food_gouda", amount: 40, mealSlot: "fruehstueck", time: "06:30" },
          { id: "pe_4_4", foodId: "food_orangensaft", amount: 200, mealSlot: "fruehstueck", time: "06:30" },
          { id: "pe_4_5", foodId: "food_kartoffel", amount: 300, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_4_6", foodId: "food_schweineschnitzel", amount: 200, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_4_7", foodId: "food_blumenkohl", amount: 150, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_4_8", foodId: "food_butter", amount: 20, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_4_9", foodId: "food_banane", amount: 120, mealSlot: "snack_nachmittag", time: "15:00" },
          { id: "pe_4_10", foodId: "food_vollkornbrot", amount: 80, mealSlot: "abendessen", time: "18:30" },
          { id: "pe_4_11", foodId: "food_rinderfilet", amount: 100, mealSlot: "abendessen", time: "18:30" },
          { id: "pe_4_12", foodId: "food_tomate", amount: 80, mealSlot: "abendessen", time: "18:30" },
          { id: "pe_4_13", foodId: "food_gurke", amount: 80, mealSlot: "abendessen", time: "18:30" },
        ],
      },
    ],
    ...ts("2026-02-20"),
  },
  {
    id: "protocol_3",
    patientId: "patient_4",
    title: "Ernährungsprotokoll Woche 1",
    type: "ernaehrungsprotokoll",
    startDate: "2026-03-03",
    endDate: "2026-03-05",
    notes: "Patient hat sich an Empfehlungen gehalten. Portionsgrößen sind noch zu hoch.",
    days: [
      {
        date: "2026-03-03",
        entries: [
          { id: "pe_5_1", foodId: "food_haferflocken", amount: 80, mealSlot: "fruehstueck", time: "07:00" },
          { id: "pe_5_2", foodId: "food_vollmilch", amount: 250, mealSlot: "fruehstueck", time: "07:00" },
          { id: "pe_5_3", foodId: "food_honig", amount: 20, mealSlot: "fruehstueck", time: "07:00" },
          { id: "pe_5_4", foodId: "food_apfel", amount: 180, mealSlot: "snack_vormittag", time: "10:00" },
          { id: "pe_5_5", foodId: "food_nudeln", amount: 300, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_5_6", foodId: "food_rinderfilet", amount: 200, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_5_7", foodId: "food_olivenoel", amount: 20, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_5_8", foodId: "food_tomate", amount: 100, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_5_9", foodId: "food_cashews", amount: 40, mealSlot: "snack_nachmittag", time: "15:00" },
          { id: "pe_5_10", foodId: "food_vollkornbrot", amount: 120, mealSlot: "abendessen", time: "19:00" },
          { id: "pe_5_11", foodId: "food_gouda", amount: 60, mealSlot: "abendessen", time: "19:00" },
          { id: "pe_5_12", foodId: "food_butter", amount: 20, mealSlot: "abendessen", time: "19:00" },
        ],
      },
      {
        date: "2026-03-04",
        entries: [
          { id: "pe_6_1", foodId: "food_vollkornbrot", amount: 100, mealSlot: "fruehstueck", time: "07:30" },
          { id: "pe_6_2", foodId: "food_ei", amount: 120, mealSlot: "fruehstueck", time: "07:30" },
          { id: "pe_6_3", foodId: "food_tomate", amount: 80, mealSlot: "fruehstueck", time: "07:30" },
          { id: "pe_6_4", foodId: "food_orange", amount: 200, mealSlot: "snack_vormittag", time: "10:00" },
          { id: "pe_6_5", foodId: "food_reis", amount: 250, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_6_6", foodId: "food_haehnchenbrust", amount: 200, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_6_7", foodId: "food_brokkoli", amount: 150, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_6_8", foodId: "food_rapsoel", amount: 15, mealSlot: "mittagessen", time: "12:00" },
          { id: "pe_6_9", foodId: "food_joghurt", amount: 200, mealSlot: "snack_nachmittag", time: "15:30" },
          { id: "pe_6_10", foodId: "food_kartoffel", amount: 250, mealSlot: "abendessen", time: "19:00" },
          { id: "pe_6_11", foodId: "food_kabeljau", amount: 180, mealSlot: "abendessen", time: "19:00" },
          { id: "pe_6_12", foodId: "food_spinat", amount: 120, mealSlot: "abendessen", time: "19:00" },
        ],
      },
      {
        date: "2026-03-05",
        entries: [
          { id: "pe_7_1", foodId: "food_haferflocken", amount: 70, mealSlot: "fruehstueck", time: "07:00" },
          { id: "pe_7_2", foodId: "food_joghurt", amount: 200, mealSlot: "fruehstueck", time: "07:00" },
          { id: "pe_7_3", foodId: "food_banane", amount: 120, mealSlot: "fruehstueck", time: "07:00" },
          { id: "pe_7_4", foodId: "food_mandeln", amount: 30, mealSlot: "snack_vormittag", time: "10:00" },
          { id: "pe_7_5", foodId: "food_kichererbsen", amount: 200, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_7_6", foodId: "food_paprika", amount: 100, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_7_7", foodId: "food_zucchini", amount: 150, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_7_8", foodId: "food_olivenoel", amount: 15, mealSlot: "mittagessen", time: "12:30" },
          { id: "pe_7_9", foodId: "food_erdbeere", amount: 150, mealSlot: "snack_nachmittag", time: "16:00" },
          { id: "pe_7_10", foodId: "food_lachs", amount: 150, mealSlot: "abendessen", time: "18:30" },
          { id: "pe_7_11", foodId: "food_kartoffel", amount: 200, mealSlot: "abendessen", time: "18:30" },
          { id: "pe_7_12", foodId: "food_gurke", amount: 100, mealSlot: "abendessen", time: "18:30" },
        ],
      },
    ],
    ...ts("2026-03-05"),
  },
];
