import { Recipe } from "@/lib/types";

const ts = { createdAt: "2026-01-01T00:00:00Z", updatedAt: "2026-01-01T00:00:00Z" };

export const RECIPES: Recipe[] = [
  {
    id: "recipe_kartoffelsuppe",
    name: "Kartoffelsuppe",
    description: "Cremige Kartoffelsuppe mit frischen Kräutern",
    category: "Suppen",
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    imageUrl: "https://images.unsplash.com/photo-1484980972926-edee96e0960d?auto=format&fit=crop&w=1200&q=80",
    prodScore: 78,
    co2PerPortion: 1.3,
    allergens: ["Sellerie"],
    additives: [],
    referenceTargets: [
      { id: "target_energy_kartoffelsuppe", label: "Energie", nutrientId: "energie", unit: "kcal", target: 450 },
      { id: "target_protein_kartoffelsuppe", label: "Eiweiß", nutrientId: "eiweiss", unit: "g", target: 18 },
    ],
    sourceType: "community",
    ...ts,
    ingredients: [
      { foodId: "food_kartoffel", amount: 600 },
      { foodId: "food_zwiebel", amount: 100 },
      { foodId: "food_karotte", amount: 150 },
      { foodId: "food_vollmilch", amount: 200 },
      { foodId: "food_butter", amount: 20 },
      { foodId: "food_petersilie", amount: 10 },
      { foodId: "food_salz", amount: 3 },
    ],
    instructions: [
      "Kartoffeln schälen und in kleine Würfel schneiden.",
      "Zwiebel und Karotten schälen und fein würfeln.",
      "Butter in einem großen Topf erhitzen und Zwiebeln glasig dünsten.",
      "Karotten und Kartoffeln dazugeben, mit 800 ml Wasser aufgießen und 25 Minuten köcheln lassen.",
      "Die Suppe teilweise pürieren, Milch einrühren und mit Salz und Petersilie abschmecken.",
    ],
  },
  {
    id: "recipe_haferbrei",
    name: "Haferbrei mit Beeren",
    description: "Warmer Haferbrei mit frischen Beeren und Honig",
    category: "Frühstück",
    servings: 1,
    prepTime: 5,
    cookTime: 10,
    imageUrl: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&w=1200&q=80",
    prodScore: 82,
    co2PerPortion: 0.6,
    allergens: ["Milch"],
    additives: [],
    referenceTargets: [
      { id: "target_energy_haferbrei", label: "Energie", nutrientId: "energie", unit: "kcal", target: 350 },
      { id: "target_fiber_haferbrei", label: "Ballaststoffe", nutrientId: "ballaststoffe", unit: "g", target: 8 },
    ],
    sourceType: "personal",
    ...ts,
    ingredients: [
      { foodId: "food_haferflocken", amount: 60 },
      { foodId: "food_vollmilch", amount: 200 },
      { foodId: "food_heidelbeere", amount: 50 },
      { foodId: "food_erdbeere", amount: 50 },
      { foodId: "food_honig", amount: 15 },
      { foodId: "food_banane", amount: 50 },
    ],
    instructions: [
      "Haferflocken mit Milch in einen kleinen Topf geben und aufkochen.",
      "Bei niedriger Hitze 5 Minuten unter Rühren köcheln lassen.",
      "Banane in Scheiben schneiden.",
      "Haferbrei in eine Schüssel füllen, mit Beeren und Bananenscheiben garnieren und mit Honig beträufeln.",
    ],
  },
  {
    id: "recipe_gemuese_reis",
    name: "Gemüsepfanne mit Reis",
    description: "Bunte Gemüsepfanne mit Paprika, Zucchini und Reis",
    category: "Hauptgerichte",
    servings: 2,
    prepTime: 15,
    cookTime: 20,
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
    prodScore: 74,
    co2PerPortion: 1.8,
    allergens: [],
    additives: [],
    referenceTargets: [
      { id: "target_energy_gemuese", label: "Energie", nutrientId: "energie", unit: "kcal", target: 500 },
      { id: "target_protein_gemuese", label: "Eiweiß", nutrientId: "eiweiss", unit: "g", target: 20 },
    ],
    sourceType: "community",
    ...ts,
    ingredients: [
      { foodId: "food_reis", amount: 300 },
      { foodId: "food_paprika", amount: 150 },
      { foodId: "food_zucchini", amount: 200 },
      { foodId: "food_brokkoli", amount: 150 },
      { foodId: "food_zwiebel", amount: 80 },
      { foodId: "food_knoblauch", amount: 5 },
      { foodId: "food_olivenoel", amount: 15 },
      { foodId: "food_salz", amount: 2 },
    ],
    instructions: [
      "Reis nach Packungsanleitung kochen.",
      "Gemüse waschen und in mundgerechte Stücke schneiden, Zwiebel und Knoblauch fein hacken.",
      "Olivenöl in einer großen Pfanne erhitzen, Zwiebel und Knoblauch kurz anbraten.",
      "Brokkoli hinzufügen und 3 Minuten braten, dann Paprika und Zucchini dazugeben.",
      "Weitere 5–7 Minuten braten, bis das Gemüse bissfest ist. Mit Salz würzen.",
      "Gemüsepfanne mit dem gekochten Reis servieren.",
    ],
  },
  {
    id: "recipe_haehnchen_salat",
    name: "Hähnchen-Salat",
    description: "Frischer Salat mit gegrillter Hähnchenbrust und Gemüse",
    category: "Salate",
    servings: 2,
    prepTime: 15,
    cookTime: 15,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
    prodScore: 88,
    co2PerPortion: 2.4,
    allergens: [],
    additives: [],
    referenceTargets: [
      { id: "target_energy_salad", label: "Energie", nutrientId: "energie", unit: "kcal", target: 420 },
      { id: "target_protein_salad", label: "Eiweiß", nutrientId: "eiweiss", unit: "g", target: 30 },
    ],
    sourceType: "personal",
    ...ts,
    ingredients: [
      { foodId: "food_haehnchenbrust", amount: 250 },
      { foodId: "food_tomate", amount: 150 },
      { foodId: "food_gurke", amount: 150 },
      { foodId: "food_paprika", amount: 100 },
      { foodId: "food_olivenoel", amount: 20 },
      { foodId: "food_spinat", amount: 80 },
    ],
    instructions: [
      "Hähnchenbrust mit etwas Olivenöl in einer Pfanne von beiden Seiten je 6–7 Minuten braten.",
      "Hähnchenbrust kurz ruhen lassen, dann in Streifen schneiden.",
      "Tomaten, Gurke und Paprika waschen und in mundgerechte Stücke schneiden.",
      "Spinat waschen und auf zwei Tellern verteilen.",
      "Gemüse und Hähnchenstreifen auf dem Spinat anrichten und mit dem restlichen Olivenöl beträufeln.",
    ],
  },
  {
    id: "recipe_lachs_brokkoli",
    name: "Lachs mit Brokkoli",
    description: "Gebratenes Lachsfilet mit gedämpftem Brokkoli",
    category: "Hauptgerichte",
    servings: 2,
    prepTime: 10,
    cookTime: 15,
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
    prodScore: 91,
    co2PerPortion: 3.5,
    allergens: ["Fisch"],
    additives: [],
    referenceTargets: [
      { id: "target_energy_lachs", label: "Energie", nutrientId: "energie", unit: "kcal", target: 550 },
      { id: "target_omega_lachs", label: "Omega-3", nutrientId: "ungesaettigte_fettsaeuren", unit: "g", target: 10 },
    ],
    sourceType: "institution",
    ...ts,
    ingredients: [
      { foodId: "food_lachs", amount: 300 },
      { foodId: "food_brokkoli", amount: 400 },
      { foodId: "food_olivenoel", amount: 10 },
      { foodId: "food_salz", amount: 2 },
      { foodId: "food_kartoffel", amount: 300 },
    ],
    instructions: [
      "Kartoffeln schälen, vierteln und in Salzwasser 20 Minuten kochen.",
      "Brokkoli in Röschen teilen und 8 Minuten dampfgaren.",
      "Lachsfilets mit Salz würzen, in einer Pfanne mit Olivenöl bei mittlerer Hitze von jeder Seite 4 Minuten braten.",
      "Lachs mit Brokkoli und Kartoffeln anrichten.",
    ],
  },
  {
    id: "recipe_linseneintopf",
    name: "Linseneintopf",
    description: "Herzhafter Linseneintopf mit Gemüse",
    category: "Eintöpfe",
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
    prodScore: 85,
    co2PerPortion: 1.1,
    allergens: [],
    additives: [],
    referenceTargets: [
      { id: "target_energy_linsen", label: "Energie", nutrientId: "energie", unit: "kcal", target: 480 },
      { id: "target_fiber_linsen", label: "Ballaststoffe", nutrientId: "ballaststoffe", unit: "g", target: 12 },
    ],
    sourceType: "community",
    ...ts,
    ingredients: [
      { foodId: "food_rote_linsen", amount: 400 },
      { foodId: "food_karotte", amount: 200 },
      { foodId: "food_kartoffel", amount: 300 },
      { foodId: "food_zwiebel", amount: 100 },
      { foodId: "food_knoblauch", amount: 5 },
      { foodId: "food_olivenoel", amount: 15 },
      { foodId: "food_tomate", amount: 200 },
      { foodId: "food_salz", amount: 3 },
    ],
    instructions: [
      "Zwiebel und Knoblauch schälen und fein hacken.",
      "Karotten und Kartoffeln schälen und in kleine Würfel schneiden.",
      "Olivenöl in einem großen Topf erhitzen, Zwiebel und Knoblauch anschwitzen.",
      "Karotten und Kartoffeln dazugeben und 2 Minuten mitbraten.",
      "Linsen und gewürfelte Tomaten hinzufügen, mit 800 ml Wasser aufgießen.",
      "25 Minuten bei mittlerer Hitze köcheln lassen, bis Linsen und Gemüse weich sind. Mit Salz abschmecken.",
    ],
  },
  {
    id: "recipe_vollkornbrot_quark",
    name: "Vollkornbrot mit Quark",
    description: "Kräftige Vollkornbrotscheiben mit Magerquark und Gemüse",
    category: "Frühstück",
    servings: 1,
    prepTime: 5,
    cookTime: 0,
    imageUrl: "https://images.unsplash.com/photo-1493770348161-369560ae357d?auto=format&fit=crop&w=1200&q=80",
    prodScore: 72,
    co2PerPortion: 0.5,
    allergens: ["Gluten", "Milch"],
    additives: [],
    referenceTargets: [
      { id: "target_energy_vollkornbrot", label: "Energie", nutrientId: "energie", unit: "kcal", target: 320 },
      { id: "target_protein_vollkornbrot", label: "Eiweiß", nutrientId: "eiweiss", unit: "g", target: 25 },
    ],
    sourceType: "personal",
    ...ts,
    ingredients: [
      { foodId: "food_vollkornbrot", amount: 100 },
      { foodId: "food_magerquark", amount: 80 },
      { foodId: "food_tomate", amount: 80 },
      { foodId: "food_gurke", amount: 60 },
      { foodId: "food_salz", amount: 1 },
    ],
    instructions: [
      "Vollkornbrot in Scheiben schneiden.",
      "Magerquark gleichmäßig auf die Brotscheiben streichen.",
      "Tomaten und Gurke in dünne Scheiben schneiden und auf dem Quark anrichten.",
      "Mit einer Prise Salz würzen und servieren.",
    ],
  },
  {
    id: "recipe_pasta_tomate",
    name: "Pasta mit Tomatensauce",
    description: "Klassische Pasta mit frischer Tomatensauce und Knoblauch",
    category: "Hauptgerichte",
    servings: 2,
    prepTime: 10,
    cookTime: 20,
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
    prodScore: 64,
    co2PerPortion: 2.9,
    allergens: ["Gluten", "Milch"],
    additives: [],
    referenceTargets: [
      { id: "target_energy_pasta", label: "Energie", nutrientId: "energie", unit: "kcal", target: 650 },
      { id: "target_sodium_pasta", label: "Natrium", nutrientId: "natrium", unit: "mg", target: 700 },
    ],
    sourceType: "community",
    ...ts,
    ingredients: [
      { foodId: "food_nudeln", amount: 400 },
      { foodId: "food_tomate", amount: 400 },
      { foodId: "food_zwiebel", amount: 80 },
      { foodId: "food_knoblauch", amount: 10 },
      { foodId: "food_olivenoel", amount: 20 },
      { foodId: "food_salz", amount: 3 },
      { foodId: "food_gouda", amount: 40 },
    ],
    instructions: [
      "Nudeln in reichlich Salzwasser nach Packungsanleitung kochen.",
      "Zwiebel und Knoblauch fein hacken und in Olivenöl glasig dünsten.",
      "Tomaten grob würfeln, dazugeben und 15 Minuten bei mittlerer Hitze einkochen lassen.",
      "Sauce mit Salz abschmecken und mit den abgetropften Nudeln vermengen.",
      "Mit geriebenem Gouda bestreut servieren.",
    ],
  },
];
